import type { Metadata } from "next";
import Link from "next/link";
import { LogoMark } from "@/components/app-preview";

export const metadata: Metadata = { title: "Atten FAQ | Local text-to-speech", description: "Answers about Atten's offline text-to-speech app, privacy, voices, platforms, licensing, and how it compares with cloud TTS." };

const faqs = [
  ["What is Atten?", "Atten is a free, open-source text-to-speech app for Mac, Windows, and the command line. It uses a bundled local speech model so you can turn text into MP3 or WAV audio without a cloud service."],
  ["Does Atten work offline?", "Yes. The published desktop app includes the engine and model. Once installed, synthesis and export can work without an internet connection."],
  ["Is Atten free?", "Yes. Atten is free and open source under the GNU GPL v3 or later. It does not require an account, subscription, API key, or per-character payment."],
  ["How does Atten compare with ElevenLabs?", "ElevenLabs is a hosted voice platform with cloud-based generation. Atten is for the different use case where you want local processing, predictable cost, offline access, and control over your text and audio. Choose based on whether you prefer a managed cloud service or local software."],
  ["How does Atten compare with Speechify?", "Speechify is a cloud-oriented reading and productivity product. Atten is a local desktop studio and CLI for generating speech files on your own computer. Atten is especially suited to private documents, offline workflows, and developers who want a scriptable tool."],
  ["What model and voices does Atten use?", "Atten ships with Kokoro 82M and provides 37 voices across American and British English, plus eight more languages. See the repository's model attribution and voice catalog for current details."],
  ["What platforms are supported?", "The current desktop releases support Apple Silicon Macs running macOS 14 or newer and 64-bit Windows 10 version 1809 or newer, including Windows 11. The CLI is documented separately."],
  ["Why does macOS say it cannot verify Atten?", "Atten is not yet notarized by Apple, so macOS blocks the first launch with a warning that it could not verify the app. To open it, double-click Atten and dismiss the warning, then open System Settings, go to Privacy & Security, scroll to Security, and choose Open Anyway. You only do this once. On macOS 15 and newer this is the only route; the older Control-click and Open shortcut no longer works for apps that are not notarized."],
  ["Where is my data stored?", "Your text, projects, and generated audio are processed locally. Project metadata is stored in your platform's Atten application-support directory and exports are kept in the app's local export location. See the privacy policy for more."],
  ["Can I use Atten from scripts?", "Yes. The CLI accepts inline text or files and can select voices, speed, format, output filename, playback, device, and JSON output. See the CLI guide for examples."],
  ["Who should choose Atten?", "Choose Atten if you want free local TTS, work with sensitive text, need offline generation, dislike subscriptions or usage meters, or want an open-source desktop app and CLI. A hosted provider may be a better fit if you need a large managed voice marketplace or server-side API."],
];

export default function FaqPage() { return <main className="min-h-screen bg-[#080807] text-[#e7eef8]"><header className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5"><LogoMark small/><span className="mono text-[11px] font-bold tracking-[.25em]">ATTEN</span></Link><Link href="/" className="text-sm text-[#8fa2ba] hover:text-[#5ddbff]">← Back to home</Link></header><div className="mx-auto max-w-4xl px-5 pb-24 pt-16 sm:px-8 sm:pt-24"><p className="mono text-[10px] tracking-[.22em] text-[#5ddbff]">LOCAL TTS KNOWLEDGE BASE</p><h1 className="mt-5 text-5xl font-semibold tracking-[-.06em] text-white sm:text-7xl">Atten FAQ.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#a7b6cc]">Clear answers about free offline text-to-speech, privacy, supported platforms, and choosing Atten over a hosted TTS service.</p><div className="mt-14 space-y-3">{faqs.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-white/10 bg-[#0a101b] p-6"><summary className="cursor-pointer list-none pr-8 text-lg font-semibold text-white"><span>{question}</span><span className="float-right text-[#5ddbff] transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-7 text-[#8fa2ba]">{answer}</p></details>)}</div></div><footer className="border-t border-white/8 px-5 py-8 text-center text-sm text-[#7f92aa]"><Link href="/privacy" className="hover:text-[#5ddbff]">Privacy policy</Link><span className="mx-3">·</span><a href="https://github.com/jashdubal/atten" className="hover:text-[#5ddbff]">Open source on GitHub ↗</a></footer></main>; }
